config/routes.rb
Rails.application.routes.draw do
  resources :conferences, only: [:index, :show, :new, :create] do
    resources :calls, only: [:new, :create]
  end

  root to: "conferences#index"

  get 'auth/twitter/callback', to: "sessions#create"
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
end

app/models/call.rb
class Call < ActiveRecord::Base
  belongs_to :conference
  validates_presence_of :conference
end

app/models/conference.rb
class Conference < ActiveRecord::Base
  has_many :calls

  has_many :conference_topics
  has_many :topics, through: :conference_topics

  validates_presence_of :name, :location

  def current_call
    self.calls.present? ? self.calls.first.due_date : false
  end

  def find_or_create_topic_with(name)
    if topic = Topic.find_by(name: name)
      self.topics.include?(topic) ? topic : self.topics << topic
    else
      self.topics.create(name: name)
    end
  end
end

app/models/conference_topic.rb
class ConferenceTopic < ActiveRecord::Base
  belongs_to :conference
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates_uniqueness_of :name

  has_many :conference_topics
  has_many :conferences, through: :conference_topics
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name, :provider, :uid

  def self.find_or_create_using_omniauth(auth_hash)
    return nil unless well_formatted?(auth_hash)

    User.create_with(name:      auth_hash[:info][:name],
                     provider:  auth_hash[:provider])
        .find_or_create_by uid: auth_hash[:uid]
  end

  private
  def self.well_formatted?(auth_hash)
    auth_hash.present? &&
      auth_hash.fetch(:info, {})[:name].present? &&
      auth_hash[:provider].present? &&
      auth_hash[:uid].present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  def new
    @call = Call.new conference: Conference.find(params[:conference_id])
  end

  def create
    @call = Call.new  conference_id: params[:conference_id],
                      due_date: params[:call][:due_date]

    if @call.save
      redirect_to @call.conference, notice: 'Call for Papers was successfully created.'
    else
      render :new
    end
  end
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  def index
    @conferences = Conference.all
  end

  def new
    @conference = Conference.new
  end

  def create
    @conference = Conference.new conference_params

    if @conference.save
      redirect_to @conference, notice: 'Conference was successfully created.'
    else
      render :new
    end
  end

  private
  def conference_params
    params.permit %i(name location code_of_conduct childcare
                    last_years_attendance)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_using_omniauth request.env["omniauth.auth"]
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in."
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calls/new.html.erb
<%= form_for [:conference, @call] do |f| %>
  <%= f.label :due_date %>:
  <%= f.datetime_local_field :due_date, type: "date" %><br />

  <%= f.submit %>
<% end %>

app/views/conferences/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Code of Conduct</th>
    <th>Childcare</th>
    <th>Call for Proposal</th>
  </tr>
  <% @conferences.each do |conference| %>
    <tr>
      <td>
        <%= conference.name %>
      </td>
      <td>
        <%= conference.location %>
      </td>
      <td>
        <%= conference.code_of_conduct %>
      </td>
      <td>
        <%= conference.childcare %>
      </td>
      <td>
        <% if conference.current_call %>
          conference.current_call
        <% else %>
          <%= link_to "Add CfP", new_conference_call_path(conference) %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to "Create a new conference", new_conference_path %>

app/views/conferences/new.html.erb
<%= form_for @conference do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.label :location %>:
  <%= f.text_field :location %><br />

  <%= f.label :code_of_conduct %>:
  <%= f.check_box :code_of_conduct %><br />

  <%= f.label :childcare %>:
  <%= f.check_box :childcare %><br />

  <%= f.label :last_years_attendance %>:
  <%= f.number_field :last_years_attendance %><br />

  <%= f.submit %>
<% end %>

app/views/conferences/show.html.erb
conference show

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CallbackWomenRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<% if current_user %>
  You are <%= current_user.name %>
  <%= link_to "Sign out", signout_path %>
<% else %>
  <%= link_to "Sign in with Twitter", "/auth/twitter" %>
<% end %>

<%= yield %>

</body>
</html>